print("Getting to know you!")
print( )
myName = input("What is your name?")
food = input("What is your favourite food:")
music = input("what is your favourite music artist?")
location = input("where do you live?:")

print( )
print("You are")
input(myName)
print("You're probably hungry for some")
input(food)
print("and You're definitely getting your groove on to")
input(music)
print("while living in the amazing city of")
input(location)
