food = input("name a food > ")
plant = input("name a type of plant > ")
cookingMethod = input("name a method of cooking > ")
burntFood = input("what word describes burned food? > ")
diyItem = input("Name a DIY item > ")
print( )
print( )
print( )
print("MENU")
print(cookingMethod, food, "with", burntFood, plant, "on the side with a", diyItem)
